### ISSUE TITLE
Add anti-spam matching pool donation to contribution flow

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#118]
As discussed with clr/ef team we want to make sure users include a mandatory donation to the matching pool in order to protect the round against spam. This should happen automatically when you contribute and we need to make sure it's reflected in the checkout UI. 

Outstanding questions:
- [ ] Does this require a separate transaction? Or can it be included in the message (like if you were reallocating?)
- [ ] @samajammin check with Barry/WJ/Auryn this is still the best approach. Ideally we avoid this altogether.

**Comment by samajammin** [comment]
Was this the final decision? I think we should confirm this is the route we want to go: https://forum.clr.fund/t/how-to-stop-spam-contributions/119

If anything I think this should only be required for reallocations (i.e. don't require this for contribution tx, since every user can only perform that tx once as-is).

**Comment by ryancreatescopy** [comment]
![image](https://user-images.githubusercontent.com/40891631/121189884-70d09480-c862-11eb-9f4c-9e4708e4045b.png)

**Comment by samajammin** [comment]
Closing this out - thinking between BrightID verification, gas fees & larger circuits this shouldn't be an issue: https://github.com/ethereum/clrfund/pull/221
