### ISSUE TITLE
MACI cap explanations

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#132]
https://www.notion.so/efdn/MACI-cap-explanations-813b62f5d4f6407d9907f6f7563f985c

There are certain MACI events that may cause a round to transition ahead of time (#131 + #130)

We should display a modal to users if this happens so they know what happens. It's also important that this shouldn't confuse new users.

Example modal copy:

#130 
```
"Contributions closed early – you can no longer donate! Due to the community's generosity and some technical constraints we had to close the round earlier than expected. If you already contributed, you still have time to reallocate if you need to. If you didn't get a chance to contribute, you can still help by donating to the matching pool"
```

#131 
```
"The round is officially closed – it's now too late to contribute or reallocate your donations! Due to the community's generosity and some technical constraints we had to close the round earlier than expected. You can still help by donating to the matching pool"
```

Modal should probably include a link to the article on MACI to help explain the technical constraints. 

And an [OK] button to dismiss.

**Comment by samajammin** [comment]
I think this is a good approach.  

If `maxContributors` is hit, I think we could just display this on the verify page: https://eth2clrfund.netlify.app/#/verify

If `maxMessages` is hit, this affects every user (both contributors, reallocators & recipients) so perhaps we pop the modal when anyone connects their wallet (then perhaps use local storage to hide the modal on subsequent reconnects?).

When should we pop this modal? As soon as a user connects their wallet?

**Comment by wackerow** [comment]
@samajammin If we go with a modal, I would suggest it is shown immediately after connects their wallet. 

An alternative I will suggest would be to display a banner/notice somewhere. I was thinking within the RoundInformation, since this should get ticked to "Closed" anyway, and would offer a nice place to explain why, in the event it closes early due to message constraints. This could similarly be closed out, with a flag in localStorage to hide it going forward. Personally would favor the banner over an unsolicited modal pop-up, but curious thoughts from others.
