### ISSUE TITLE
Round closed tooltip bug

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#147]
![image](https://user-images.githubusercontent.com/40891631/121672151-5e936800-caa7-11eb-9e14-432dfb0d3e35.png)

If a user doesn't contribute and we move to reallocation phase, the tooltip on "Round closed for contributions" shouldn't describe reallocation. Instead it should say that "Contributions are closed but you can still reallocate if you already contributed". This will account for users who have in fact contributed but are not yet connected.

**Comment by samajammin** [comment]
https://www.notion.so/efdn/Round-closed-tooltip-bug-301033fb8fb948c7a8824c28ec8166a2

**Comment by samajammin** [comment]
Edge cases to account for:

If in reallocation phase...
- If wallet is not connected... "you have to connect your wallet in order to reallocate. If you've contributed, please connect your wallet to proceed"
- If wallet is connected...
  - If you have contributed: explain reallocation phase
  - If you have NOT contributed: explain round is over
