### ISSUE TITLE
Cart displays reallocation message before contribution is complete

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#212]
https://www.notion.so/efdn/Cart-displays-reallocation-message-before-contribution-is-complete-3dd080d91a784677a5a6bb0183a54cf5

Noticed when testing a contribution that the reallocation displays prematurely (it displays after the 2nd of 3 txs):

![Image 2021-07-21 at 2 44 21 PM](https://user-images.githubusercontent.com/8097623/126564612-297e3a70-cab4-475a-84d9-ac960e7b1011.jpg)

We should hide this until the user's contribution flow is complete to avoid confusion.

**Comment by samajammin** [comment]
This relates to the 2nd bullet point of @wackerow's comment: https://github.com/ethereum/clrfund/issues/100#issuecomment-879418434

> On initial contribution, if user cancels the 3rd tx, the votes are not recorded but it UI displays as though the user has contributed to those projects. They are able to "reallocate" which would actually be the first allocation... the UI should reflect that the user still needs to allocate their project votes or the funds will end up in the matching pool

**Comment by pettinarip** [comment]
As @wackerow said, I think we need a new state in between the contribution tx and the sending of votes tx.

This new state should be when:
- the user has contributed (step 2)
- the user has not sent the votes yet (a failed step 3)

In this scenario, we should still display the "Contribute" button to the user in order to facilitate the user to enter again into the ContributionModal and execute the last tx (step 3, allocating the votes).
In addition to this, we could display a copy to the user (in the same place we are displaying the reallocation message, on the top of the cart) explaining that he needs to execute that final tx.

Let me know if you agree with this logic while I figure out how to implement it. @samajammin @wackerow @corwintines

**Comment by samajammin** [comment]
@pettinarip agreed!

Potential copy for that purple banner:
> Almost done! You must submit one more transaction to complete your contribution.

**Comment by corwintines** [comment]
Makes sense to me 👍
