### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#27]
Love that we have markdown support in our inputs now, but is there a way to limit what markdown is used? For example a project could start adding in a bunch of h1s which would litter the project page with h1s which would be bad stylistically and for accessibility.

![image](https://user-images.githubusercontent.com/40891631/116397270-51cff300-a81e-11eb-86b1-129624def884.png)
![image](https://user-images.githubusercontent.com/40891631/116397532-9b204280-a81e-11eb-9880-1f96d275ebaa.png)

**Comment by samajammin** [comment]
@wackerow let's investigate stripping out headers from the markdown.

Let's also explore the potential concern of the markdown rendering :face_with_monocle:  https://vuejs.org/v2/guide/security.html#Rule-No-1-Never-Use-Non-trusted-Templates

**Comment by wackerow** [comment]
https://snyk.io/vuln/npm:markdown-it - no known vulnerabilities to this package since v10 (we're running 12.0.4, latest 12.0.6).
Not sure what a better option would be.

And for the markdown, if it's just the `h1` tags we want to limit, it's probably easiest to just re-style those with css. Maybe just make them the same size as `h2` with a slightly heavier `font-weight`.
