### ISSUE TITLE
Generalize recipient application

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#429]
Currently our recipient application (https://eth2clrfund.netlify.app/#/join) is built specifically for the Eth2 round - we should generalize the functionality for any clr.fund instance.

Specifically, we have an contact email input & a Google Sheet integration to send the information there:
- Email input: https://github.com/ethereum/clrfund/blob/develop/vue-app/src/views/Join.vue#L296
- Lambda function (that pipes data to Google Sheet): https://github.com/ethereum/clrfund/blob/develop/vue-app/src/lambda/recipient.js

Is this something we should remove entirely? Or as optional, e.g. where if `GOOGLE_APPLICATION_CREDENTIALS` ENV variable exists, we include the email input & API integration?

**Comment by samajammin** [comment]
Let's go with the approach of checking for `GOOGLE_APPLICATION_CREDENTIALS`. If there's no value, let's hide the email input & not require it as part of the validation.

**Comment by wackerow** [comment]
Ended up using the variable for the google sheet ID instead of the `CREDENTIALS` variable for security reasons. The credentials variable is intentionally not exposed to the Vue front-end. The linked PR updates the "sheet ID" variable, which does not include sensitive key information, prepending it with `VUE_APP_` so it can be read by the front-end, and conditionally require an email if it is present.
