### ISSUE TITLE
Project accepted on Recipient Registry does not display on Projects page

### ISSUE THREAD

**Issue by daodesigner** [ethereum/clrfund#455]
Project shows up as Live here:
https://ethhondurasclr.on.fleek.co/#/recipients

But not here:
https://ethhondurasclr.on.fleek.co/#/projects

**Comment by pettinarip** [comment]
I think the problem comes from this line https://github.com/ethereum/clrfund/blob/develop/vue-app/src/api/recipient-registry-optimistic.ts#L375
Where we are skipping the projects if the challenge period is not over yet. We were doing this before so, I'm not sure if this is incorrect. I guess that if the request was accepted, it should be visible.

**Comment by daodesigner** [comment]
Thank you! Think you just saved me a ton of time <3 will change so that the project displays even if it can still be challenged for the optimistic registry.
