### ISSUE TITLE
Add logic to recipient submission widget

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#67]
@ryancreatescopy added styles to the `RecipientSubmissionWidget` component in #60 - this issue covers plugging in logic to support the various UI states.

- [x] Add check for low ETH funds
- [x] Read registry info from store (currently in `created()` hook): https://github.com/ethereum/clrfund/blob/develop/vue-app/src/components/RecipientSubmissionWidget.vue#L111

Related issue: #68

**Comment by ryancreatescopy** [comment]
@samajammin @wackerow bringing your attention to this.

**Comment by samajammin** [comment]
Edit: updated description

**Comment by samajammin** [comment]
Edit: broke out estimation of tx fees into separate issue (https://github.com/ethereum/clrfund/issues/151)

**Comment by corwintines** [comment]
Edit: broke out:
- Confirm tx pending state displays as expected. At the moment it redirects you straight to the success page. I believe this is due to the fact that Hardhat mines all txs immediately by default. We should test this out with a mining interval added. See Upgrade Hardhat version clrfund/monorepo#355 for how this can be accomplished.
- Add/confirm logic for isLoading, isWaiting, isWrongNetwork, isTxRejected, txError

into separate issue to check when test net deploy is out (https://github.com/ethereum/clrfund/issues/168)

**Comment by wackerow** [comment]
@corwintines This looks like it was closed with #167, is that correct?

**Comment by samajammin** [comment]
@corwintines can you please confirm? Looks like we can close this out.

I think we can. I'm closing this. Please re-open if I'm incorrect 😄
